# Generated by Django 3.2.5 on 2021-07-04 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContestantsDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ContestantName', models.CharField(max_length=80)),
                ('ProgramName', models.CharField(max_length=120)),
                ('Level', models.CharField(max_length=4)),
            ],
            options={
                'db_table': 'contestantsdetails',
            },
        ),
        migrations.CreateModel(
            name='StudentsRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=80)),
                ('IndexNumber', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'studentsregistration',
            },
        ),
        migrations.CreateModel(
            name='VoteVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IndexNumber', models.CharField(max_length=10)),
                ('ContestantName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting_app.contestantsdetail')),
            ],
            options={
                'db_table': 'votes',
            },
        ),
    ]
